import type { Lead } from '@/types/lead'

const now = Date.now()
const mins = (n: number) => new Date(now - n * 60 * 1000).toISOString()
const hours = (n: number) => new Date(now - n * 3600 * 1000).toISOString()

export const MOCK_LEADS: Lead[] = [
  {
    id: '1',
    name: 'Максим Карпов',
    username: 'maxim_karpov',
    source: 'telegram',
    sourceChat: '@freelance_ru',
    url: 'https://t.me/maxim_karpov',
    telegram: 'maxim_karpov',
    keyword: 'CRM',
    message: 'Ищу разработчика для создания CRM-системы для малого бизнеса. Бюджет 80–150к. Нужно быстро, есть ТЗ. Пишите в личку, обсудим детали.',
    status: 'new',
    isHot: true,
    createdAt: mins(5),
  },
  {
    id: '2',
    name: 'Анна Савчук',
    username: 'anna_savchuk',
    source: 'vk',
    sourceChat: 'Бизнес и маркетинг',
    url: 'https://vk.com/id329481027',
    vk_id: '329481027',
    keyword: 'SMM',
    message: 'Нужен SMM-специалист для интернет-магазина одежды. Бюджет 30к/мес, ведение + таргет Instagram и VK. Официальное ИП, всё по договору.',
    status: 'new',
    isHot: true,
    createdAt: mins(23),
  },
  {
    id: '3',
    name: 'Игорь Беляев',
    username: 'igor_belyaev_nsk',
    source: 'telegram',
    sourceChat: '@it_zakazy',
    url: 'https://t.me/igor_belyaev_nsk',
    telegram: 'igor_belyaev_nsk',
    keyword: 'сайт',
    message: 'Нужен лендинг для строительной компании. Срок 2 недели, бюджет от 30к. Есть референсы и текст. Работа под ключ.',
    status: 'new',
    isHot: false,
    createdAt: mins(47),
  },
  {
    id: '4',
    name: 'Дмитрий Иванов',
    username: 'dmitry_ivanov_msk',
    source: 'forum',
    sourceChat: 'vc.ru',
    url: 'https://vc.ru/u/dmitry_ivanov',
    keyword: 'дизайн',
    message: 'Ищу дизайнера для создания логотипа и фирменного стиля кофейни. Срок — неделя. Бюджет обсуждается, ориентир 15–25к.',
    status: 'contacted',
    isHot: false,
    note: 'Написал, жду ответа',
    createdAt: hours(2),
  },
  {
    id: '5',
    name: 'Светлана Морозова',
    username: 'sveta_morozova',
    source: 'telegram',
    sourceChat: '@digital_profi',
    url: 'https://t.me/sveta_morozova',
    telegram: 'sveta_morozova',
    email: 'sveta@morozova.biz',
    keyword: 'разработчик',
    message: 'Нужен Python-разработчик для парсинга данных с сайтов конкурентов и автоматизации отчётов в Google Sheets. Проект на 2–3 месяца.',
    status: 'new',
    isHot: false,
    createdAt: hours(3),
  },
  {
    id: '6',
    name: 'Роман Климов',
    username: 'roman_klimov_photo',
    source: 'vk',
    sourceChat: 'Фотографы России',
    url: 'https://vk.com/roman_klimov_photo',
    vk_id: '18274632',
    keyword: 'сайт',
    message: 'Нужен сайт-портфолио фотографа. Простой, красивый, с галереей и формой заказа. Бюджет до 25к, срок 10 дней.',
    status: 'new',
    isHot: false,
    createdAt: hours(5),
  },
  {
    id: '7',
    name: 'Ольга Петрова',
    username: 'olga_petclinic',
    source: 'telegram',
    sourceChat: '@biznes_pomosh',
    url: 'https://t.me/olga_petclinic',
    telegram: 'olga_petclinic',
    phone: '+79161234567',
    keyword: 'CRM',
    message: 'Ищу специалиста по настройке amoCRM для ветеринарной клиники. Нужна интеграция с сайтом и телефонией. Бюджет 40–60к.',
    status: 'replied',
    isHot: false,
    note: 'Ответила, назначила звонок на пятницу',
    createdAt: hours(8),
  },
  {
    id: '8',
    name: 'Артём Николаев',
    username: 'artem_n_business',
    source: 'forum',
    sourceChat: 'dev.by',
    url: 'https://dev.by/u/artem_n',
    keyword: 'мобильное приложение',
    message: 'Ищу команду для разработки мобильного приложения для доставки еды (MVP). React Native или Flutter. Бюджет 200–400к, есть инвестор.',
    status: 'new',
    isHot: false,
    createdAt: hours(12),
  },
]
